version: '3.8'

services:
    postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456789
            - POSTGRES_DB=realstate
        ports:
            - "6543:5432"
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data

volumes:
    database-data: